# Generated by Django 4.2.6 on 2024-05-23 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='linkPath',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
