# Generated by Django 4.2.6 on 2024-05-28 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_ostitle_oslabel'),
    ]

    operations = [
        migrations.CreateModel(
            name='OSCustomData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('OSText', models.TextField(blank=True, max_length=100000, null=True)),
                ('OSImage', models.ImageField(blank=True, null=True, upload_to='static/OSimages/')),
                ('OSLabel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='OScustom_data', to='courses.oslabel')),
            ],
        ),
    ]
