# Generated by Django 4.2.6 on 2024-05-24 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_linkpath'),
    ]

    operations = [
        migrations.AddField(
            model_name='english',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='english',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, null=True)),
                ('url', models.URLField(null=True)),
                ('english', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='courses.english')),
            ],
        ),
    ]
